# Generated by Django 5.0.3 on 2024-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fuel_name', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(choices=[('Tata', 'Tata'), ('Audi', 'Audi'), ('Toyata', 'Toyata'), ('Honda', 'Honda')], max_length=300)),
                ('Car_fuel', models.ManyToManyField(to='app.fueltypemodel')),
            ],
        ),
    ]
